### ISSUE TITLE
Does not install under older SFOS releases

### ISSUE THREAD

**Issue by Olf0** [szopin/harbour-discourser#12]
... due to well documented [changes in the RPM compression as of SFOS 4.5.0](https://forum.sailfishos.org/t/sfos-4-5-0-switches-rpm-compression-what-does-that-mean-for-existing-rpms/13153).

I would have added this to the `.spec` file resolving the issue:
```
# Define (S)RPM compression sensibly, taking compatibility into account, see
# https://github.com/sailfishos-patches/patchmanager/pull/417#issuecomment-1429068156
%define _source_payload w6.gzdio
%define _binary_payload w2.xzdio
```

But Spectacle is used, which relies on a coarsly [documented YAML syntax](https://github.com/mer-tools/spectacle#readme).
[Specifically stating](https://github.com/mer-tools/spectacle?tab=readme-ov-file#syntax-of-spectacle-yaml):
```
● Macros: list of string
● Macros2: list of string
```
O.K.?!?

At least the [syntax for the placeholders](https://github.com/mer-tools/spectacle?tab=readme-ov-file#customizations-in-spec) is clear:
Either
```
  # >> macros
  # << macros
```
or
```
  # >> macros2
  # << macros2
```
But what is the difference between `macros` and `macros2`?

Consequently, I have no idea how to back-translate `%defines` in a `.spec` file to a Spectacle `.yml` file.

P.S.: But I am more convinced than ever to avoid Spectacle wherever I can (none of my projects uses it), primarily due to it being not well documented.

P.P.S.: I ultimately found that I already had researched and [documented this](https://forum.sailfishos.org/t/sfos-4-5-0-switches-rpm-compression-what-does-that-mean-for-existing-rpms/13153/23).

**Comment by szopin** [comment]
Closed by https://github.com/szopin/harbour-discourser/commit/3951a9f72e727c094c943e4c393513ae232e94bf hopefully

**Comment by Olf0** [comment]
> Closed by [3951a9f](https://github.com/szopin/harbour-discourser/commit/3951a9f72e727c094c943e4c393513ae232e94bf) hopefully

No, [commmit 3951a9f](https://github.com/szopin/harbour-discourser/commit/3951a9f72e727c094c943e4c393513ae232e94bf) is completely unrelated to RPM compression, and PR #14 reverted the formerly merged PR #13: The latter action closed this issue (#12), but merging PR #14 revived it.

Consequently this issue is not addressed at all in the current state of the `master` branch.

P.S.: What was your consideration to revert PR #13 by PR #14?

**Comment by szopin** [comment]
Your commit caused the build to fail so reverted it and added define in spec that should result in the same, if you hve a working commit then pls contribute 

On Thursday, 15 February 2024, olf wrote:
> > Closed by [3951a9f](https://github.com/szopin/harbour-discourser/commit/3951a9f72e727c094c943e4c393513ae232e94bf) hopefully
> 
> No, [commmit 3951a9f](https://github.com/szopin/harbour-discourser/commit/3951a9f72e727c094c943e4c393513ae232e94bf) is completely unrelated to RPM compression, and PR #14 reverted the formerly merged PR #13: The latter action closed this issue (#12), but merging PR #14 revived it.
> Consequently this issue is currently not addressed at all.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-discourser/issues/12#issuecomment-1946885004
> You are receiving this because you modified the open/close state.
> 
> Message ID: ***@***.***

-- 
Sent from my Jolla

**Comment by szopin** [comment]
Oh wow, just noticed the spec change got overwritten it seems

On Thursday, 15 February 2024, olf wrote:
> > Closed by [3951a9f](https://github.com/szopin/harbour-discourser/commit/3951a9f72e727c094c943e4c393513ae232e94bf) hopefully
> 
> No, [commmit 3951a9f](https://github.com/szopin/harbour-discourser/commit/3951a9f72e727c094c943e4c393513ae232e94bf) is completely unrelated to RPM compression, and PR #14 reverted the formerly merged PR #13: The latter action closed this issue (#12), but merging PR #14 revived it.
> Consequently this issue is currently not addressed at all.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-discourser/issues/12#issuecomment-1946885004
> You are receiving this because you modified the open/close state.
> 
> Message ID: ***@***.***

-- 
Sent from my Jolla

**Comment by szopin** [comment]
Yeah just witnessed it, if you modify only spec file it compiles with the define just fine, if you touch the yaml file too the spec file gets overwritten and %define _binary_payload w2.xzdio gets lost, no freaking clue why that happens, probably will get lost on next release no idea, updating openrepos rpm right now so check if it works now

**Comment by Olf0** [comment]
> Your commit caused the build to fail 

Sorry, I assumed that minimal change to be working.  As I do not like and use Spectacle I never tested it.

> so reverted it 

That is well understandable.

> and added define in spec that should result in the same, 

Yes, and this is well tested, but you are using Spectacle, hence …

> … just noticed the spec change got overwritten …

---------------

> if you hve a working commit then pls contribute

<sup>Generally, I would advise not to use Spectacle, as it never made any sense to me not to write `.spec` files by hand: IMO it is just a superfluous indirection, which does not make anything easier (as it was originally intended), rather the opposite.  Furthermore, Spectacle is obviously underdocumented (especially lacks comprehensive examples) and basically out of maintenance for a decade.  Recently Jolla started to cease using Spectacle in their own builds processes, so they are phasing it out.</sup>

Unfortunately I have nothing else than what I researched years ago and documented at FSO.  But I would be interested in knowing, what exactly happens, as this may be easily resolvable.  As you do not build Discourser by a GitHub workflow, I cannot see what "your commit caused the build to fail" exactly means.  Can you please copy&paste the exact error message, denot when i the build process this is emitted and how the `.spec` file created by Spectacle looks like: This *should* result in exactly the `%define` statement I documented and which you successfully used by directly putting it into the `.spec` file (until it becomes overwritten by the next Spoectacle run).

------------------------------------

> updating openrepos rpm right now so check if it works now

This RPM file installs flawlessly on SailfishOS 3.2.1.
<sub>Discourser also seems to be running on this old SFOS release; apparently the code does not use anything which requires a newer SFOS.</sub>

Thank you very much.

P.S.: It may make sense to reopen this issue, because only manually crafted builds do work on older SFOS releases, as you have experienced with the current "code base" / configuration.
